"""empty message

Revision ID: 925b1afceff1
Revises: c27768bd85ec
Create Date: 2022-11-09 12:38:21.643811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '925b1afceff1'
down_revision = 'c27768bd85ec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('finance', sa.Column('deskripsi', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('finance', 'deskripsi')
    # ### end Alembic commands ###
